### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by connerbw**

### CODE REVIEW

**Comment by connerbw** [comment]
Sorry, I was trying to fork back into our own repo. 

Would be great if you were interested in these changes. I will be working on this over the course of this week.

**Comment by stuartlewis** [comment]
Hi!

Thanks - it's good to see this code getting reused.  Happy to accept some/much of it vis a pull request, or we could publicise your version as a more up to date version if that is easier?

Just a curious question: how is Pressbooks planning on using SWORD?

Thanks,


Stuart

**Comment by greatislander** [comment]
Hi @stuartlewis! We (@connerbw, senior developer @pressbooks, and myself, lead developer @pressbooks) are working on a project with [eCampusOntario](https://www.ecampusontario.ca/Content/about-ecampusontario) and Ryerson University to expand Pressbooks' capacity as an open platform for textbook authoring publishing. One key component of this is an add-on plugin which would allow Pressbooks users to authenticate with, and submit textbooks to, a DSpace repository. We settled on SWORD as the best tool for this, hence our work with your library. We're building our integration in [pressbooks/excalibur](https://github.com/pressbooks/excalibur) (mostly scaffolding at this point but @connerbw is working on the initial release this week).

**Comment by stuartlewis** [comment]
Hi - thanks for your reply.  The code was mainly developed against DSpace, so hopefully you'll find it reasonably robust.  SWORD v1 is probably more battle-tested than v2, but for reasonably simple use case you shouldn't have any troubles.  Good luck with the work!

**Pull request closed without merging**
